//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POA.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agent
    {
        public Agent()
        {
            this.Principal_Agent = new HashSet<Principal_Agent>();
            this.Principal_Agent1 = new HashSet<Principal_Agent>();
        }
    
        public int Agent_ID { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Middle_Name { get; set; }
        public string City { get; set; }
        public string KifleKetema { get; set; }
        public string Wereda { get; set; }
        public string House_No { get; set; }
        public string ID_No { get; set; }
        public int Country_Of_Birth_ID { get; set; }
        public int Country_Of_CitizenShip_ID { get; set; }
        public int Country_Of_Residence_ID { get; set; }
        public int Title_ID { get; set; }
        public string Email { get; set; }
        public string Phone_No { get; set; }
    
        public virtual Agent Agent1 { get; set; }
        public virtual Agent Agent2 { get; set; }
        public virtual Country Country { get; set; }
        public virtual Country Country1 { get; set; }
        public virtual Country Country2 { get; set; }
        public virtual Title Title { get; set; }
        public virtual ICollection<Principal_Agent> Principal_Agent { get; set; }
        public virtual ICollection<Principal_Agent> Principal_Agent1 { get; set; }
    }
}
