//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POA.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category_SubCategory
    {
        public Category_SubCategory()
        {
            this.Principal_Agent_Category_SubCategory = new HashSet<Principal_Agent_Category_SubCategory>();
        }
    
        public int Category_SubCategory_ID { get; set; }
        public int Category_ID { get; set; }
        public int SubCategory_ID { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual SubCategory SubCategory { get; set; }
        public virtual ICollection<Principal_Agent_Category_SubCategory> Principal_Agent_Category_SubCategory { get; set; }
    }
}
