//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POA.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public Country()
        {
            this.Agents = new HashSet<Agent>();
            this.Agents1 = new HashSet<Agent>();
            this.Agents2 = new HashSet<Agent>();
        }
    
        public int Country_ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Agent> Agents { get; set; }
        public virtual ICollection<Agent> Agents1 { get; set; }
        public virtual ICollection<Agent> Agents2 { get; set; }
    }
}
