//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POA.Domain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class POADBEntities : DbContext
    {
        public POADBEntities()
            : base("name=POADBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Category_SubCategory> Category_SubCategory { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<LogAction> LogActions { get; set; }
        public virtual DbSet<Principal_Agent> Principal_Agent { get; set; }
        public virtual DbSet<Principal_Agent_Category_SubCategory> Principal_Agent_Category_SubCategory { get; set; }
        public virtual DbSet<SubCategory> SubCategories { get; set; }
        public virtual DbSet<Template> Templates { get; set; }
        public virtual DbSet<Title> Titles { get; set; }
        public virtual DbSet<Agent> Agents { get; set; }
    }
}
