//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POA.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Principal_Agent_Category_SubCategory
    {
        public int Principal_Agent_Category_SubCategory_ID { get; set; }
        public int Principal_Agent_ID { get; set; }
        public int Category_SubCategory_ID { get; set; }
    
        public virtual Category_SubCategory Category_SubCategory { get; set; }
        public virtual Principal_Agent Principal_Agent { get; set; }
    }
}
