//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POA.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Template
    {
        public Template()
        {
            this.Principal_Agent = new HashSet<Principal_Agent>();
        }
    
        public int Template_ID { get; set; }
        public string Name { get; set; }
        public string Content { get; set; }
        public string Title { get; set; }
        public string Header { get; set; }
    
        public virtual ICollection<Principal_Agent> Principal_Agent { get; set; }
    }
}
