//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POA.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Title
    {
        public Title()
        {
            this.Agents = new HashSet<Agent>();
        }
    
        public int Title_ID { get; set; }
        public string Title_Name { get; set; }
        public string Title_Description { get; set; }
    
        public virtual ICollection<Agent> Agents { get; set; }
    }
}
